#!/bin/bash
trap unlock_on_exit EXIT INT TERM

compiler="COMPILER_NAME"
compiler_original="${compiler}-original"
all_options=("$@")
infer_dir="/tmp/infer-out"
skip_capture=false
lock_dir="/tmp/infer.lockdir"
pid_file="${lock_dir}/PID"

function lock {
  mkdir "${lock_dir}" > /dev/null 2>&1 && echo $$ > ${pid_file}
}

# unlocks the lock even if this process isnt the owner
function unlock {
  PID=$(cat ${pid_file} 2>&1)
  rm -rf ${lock_dir}
}

# checks if the lock owner still exists -- if not, the lock is removed
function lock_failed {
  PID=$(cat ${pid_file} 2>&1)  # 2>&1 -- do not print anything if cat fails

  # an error while reading PID file, e.g. PID file wasnt created yet
  if [ $? != 0 ]; then
    return
  fi

  # lock owner doesnt exist anymore -- remove the lock
  if ! kill -0 ${PID} &>/dev/null; then
    unlock
  fi
}

# checks if the lock owner is this script -- if so, the lock is removed
function unlock_on_exit {
  PID=$(cat ${pid_file} 2>&1)  # 2>&1 -- do not print anything if cat fails

  # if PID file was loaded correctly
  if [ $? == 0 ]; then
    # if this script still owns the lock then remove it
    if [ "$$" == "${PID}" ]; then
      unlock
    fi
  fi

  # restore all passed options
  set -- "${all_options[@]}"

  # return code is carried back to a caller
  ${compiler_original} "$@"
  exit $?
}

if [[ $# -eq 1 && "$1" == *"@/tmp/"* ]] ;
then
  skip_capture=true
  set -- "/usr/bin/${compiler_original}"
fi

for var in "$@"
do
    if [[ "$var" =~ conftest[0-9]*\.c$ ]] ;
    then
      skip_capture=true
    fi
done

if [ "${skip_capture}" = false ]
then
  # delete incompatible options of Infers clang
  for arg do
    shift
    [ "$arg" = "-fstack-clash-protection" ] && continue
    [ "$arg" = "-flto=auto" ] && continue
    [ "$arg" = "-flto=jobserver" ] && continue
    [ "$arg" = "-ffat-lto-objects" ] && continue
    [[ "$arg" =~ "-flto-jobs=[0-9]*" ]] && continue
    [ "$arg" = "-flto=thin" ] && continue
    [ "$arg" = "-flto=full" ] && continue
    [ "$arg" = "-fsplit-lto-unit" ] && continue
    [ "$arg" = "-fvirtual-function-elimination" ] && continue
    [ "$arg" = "-flto=full" ] && continue
    [ "$arg" = "-fwhole-program-vtables" ] && continue
    [ "$arg" = "-fno-leading-underscore" ] && continue
    [ "$arg" = "-mno-avx256-split-unaligned-load" ] && continue
    [ "$arg" = "-mno-avx256-split-unaligned-store" ] && continue
    set -- "$@" "$arg"
  done

  # critical section
  while :
  do
    if lock
    then
      # lock acquired
      # logging
      >&2 echo ""
      >&2 echo "NOTE: INFER: ${compiler}-wrapper: running capture phase"
      if infer capture --reactive -o ${infer_dir} --force-integration cc -- ${compiler} "$@" 1>&2
      then
        >&2 echo "NOTE: INFER: ${compiler}-wrapper: successfully captured: \"${compiler} $@\""
      else
        >&2 echo "WARNING: INFER: ${compiler}-wrapper: unsuccessfully captured: \"${compiler} $@\""
      fi
      >&2 echo ""

      # the script terminates in the unlock function
      unlock
      break
    #else
      # lock_failed
    fi
  done
fi
